steps:
  # Set a persistent volume according to /cloud-build/docs/build-config (search for volumes)
  - name: 'ubuntu'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
    args: ['cp', '-a', '.', '/persistent_volume']

  # Build APK with Gradle Image from mounted /persistent_volume using name: vol1
  - name: 'gcr.io/cloud-builders/docker'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
    args: ['run', '-v', 'vol1:/home/networksurvey', '--rm', 'gcr.io/fullstackgcp/gradle', '/bin/sh', '-c', 'cd /home/networksurvey && ./gradlew clean assembleDebug']

  # Push the APK Output from vol1 to your GCS Bucket with Short Commit SHA.
  - name: 'gcr.io/cloud-builders/gsutil'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
    args: ['cp', '/persistent_volume/networksurvey/build/outputs/apk/debug/*', 'gs://network-survey-builds/']

timeout: 1200s